spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCLCDB
    username: sys as sysdba
    password: mypassword1
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: SYS
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    default-schema: SYS
    clean-on-validation-error: true 